
- name: Infrastructure
  hosts: test
  roles:
    - name: docker
    - name: openldap
    - name: Traefik

- name: Install applications
  hosts: whoami
  roles:
    - name: whoami


- name: Install applications
  hosts: whoami
  roles:
    - name: nginx

- name: Install applications
  hosts: whoami
  roles:
    - name: apache


