
- name: Infrastructure
  hosts: test
  roles:
    - name: docker
    - name: openldap
    - name: Traefik

- name: Install applications
  hosts: groupe1,groupe2,groupe3
  roles:
    - name: whoami




